title:            'Wax Demo'
description:      'Minimal Exhibitions with Jekyll'
url:              'https://mnyrop.github.io'
baseurl:          '/wax-kit'
copyright:        ''

theme: wax-theme
source: source

collections:
  panoramas:
    output: true
    build:
      simple_images:
      iiif:
      pages:

