title:            'Wax Demo'
description:      'Minimal Exhibitions with Jekyll'
url:              'https://mnyrop.github.io'
baseurl:          '/wax-kit'
copyright:        ''

theme: wax_theme
source: source
search_dir: search
collections_dir: ''

collections:
  demo:
    output: true
    sort_by: order
    data:
      assets: 'assets'
      records: 'records.csv'
      dictionary: 'dictionary.yml'
    build:
      simple_images:
        variants:
          full: 1140
          thumbnail: 400
      iiif:
        scale_factors: []
        exclude: []
      pages: 
        layout: item
      search:
        exclude: []
        index: '/search/index/demo.json'
