title:            'Wax Demo'
description:      'Minimal Exhibitions with Jekyll'
url:              'https://mnyrop.github.io'
baseurl:          '/wax-kit'
copyright:        ''

theme: wax_theme
source: source
search_dir: search
collections_dir: ''

search:
  site:
    index: 'wax/search/site.json'
    full_site: true
  demo:
    index: 'wax/search/demo.json'
    collections: [demo]

collections:
  demo:
    output: true
    sort_by: order
    data:
      assets: 'assets'
      records: 'records.csv'
      dictionary: 'dictionary.yml'
    build:
      simple_images:
        variants:
          full: 1140
          thumbnail: 400
      iiif:
        scale_factors: []
      pages: 
        layout: item
      search:
        index: '/search/index/demo.json'
