title:            'Wax Demo'
description:      'Minimal Exhibitions with Jekyll'
url:              'https://mnyrop.github.io/wax-kit'
baseurl:          ''
copyright:        ''

theme: wax_theme
source: src

collections:
  demo:
    output: true
    wax:
      build:
        simple_images:
        iiif:
        pages: 
        search:
